// TODO: Will be removed
export default [
  {
    title: 'Personal Data Protection Policy (“Privacy Policy”)',
    body: 'MSIG Insurance (Singapore) Pte. Ltd. (“MSIG”, “we’, “us”) is committed to complying with the Personal Data Protection Act 2012.  We set out herein our Privacy Policy to assure you of our commitment.',
  },
  {
    title: 'Privacy Policy',
    body: 'MSIG takes and values your privacy very seriously.  To ensure that your personal information is secure, we communicate and enforce our privacy and security guidelines according to the Personal Data Protection Act 2012 (“the Act”). \n We take precautions to safeguard your personal information against loss, theft, misuse, as well as against unauthorized access, collection, use, disclosure, copying, modification, disposal, or similar risks.  We impose very strict sanction controls and only authorized staff on a need-to-know basis is given access to or will handle your personal data.  We provide regular training to all staff on this Policy, and to keep them abreast of any new development in privacy laws and regulations in Singapore. \n MSIG collects, uses and discloses your personal data only for the purpose of providing you with the services and benefits of your membership account with us and/or your insurance policy purchased from us, including when handling a claim made by you and for conducting customer surveys.  In this regard, we may disclose your personal data to business partners (including reinsurers, brokers and bank partners), associates and third party service providers when reasonably necessary, and on a need-to-know basis.  We will require these parties to protect personal data they may receive from us in a manner consistent with this Policy.  We do not allow them to use the personal data for any other purpose. We will not sell your personal data to any person for any reason. \nAs a global insurance group, we may disclose your personal data to our related or affiliated companies in the MSIG Group or MS&AD Group, our regional holding company, and/or our parent company.  We will also ensure that such disclosure will only be done when absolutely necessary, and will be in accordance with this Policy. \nWe may also share your personal data with other insurers as part of the industry’s efforts for proper underwriting and proper administration of claims. \nWith effect from 2 Jan 2014, as a new customer of MSIG, we will obtain your consent to send you marketing and promotional materials via SMS and phone calls. For existing MSIG customers, we will continue to send you marketing and promotional materials through these means unless you advise us otherwise. We will also send to all customers marketing and promotional materials by direct mail or email, which you may unsubscribe any time. \nIf you are a third party making a claim against us and/or our policyholders, we will collect, use and disclose your personal data for the purpose of handling your claim.  This may include disclosing your personal data to third party service providers and other insurers, for proper underwriting and proper administration of claims, when reasonably necessary. \nWe will retain your personal data for a period that is no longer than necessary for business or statutory purposes.',
  },
  {
    title: 'Transactions over the Internet',
    body: 'When you transact with us over the Internet, in addition to your personal data, we receive and store certain types of information, e.g. your IP address, browser type, domain names, access times and referring Web site addresses.  This is accomplished by the use of tracking technologies provided by media agencies.  The information collected is used for the operation of our service, to maintain the quality of our service, and to provide general statistics regarding usage of our website.  No personally identifiable data is used for this purpose. \nWhen credit account details and other transactional data you provide to us are transmitted over the Internet, it is protected.  Industry standard Secure Socket Layer (SSL) communication protocol is the de facto cryptographic standard that we use for securing data communication between the browser and our website.',
  },
  {
    title: 'Your right',
    body: 'Under the Act, you have the right to request for information about your personal data that is in our possession or under our control.  You can also request for information about the ways in which your personal data has been or may have been used or disclosed by us.  An administrative fee will be imposed on you for the request. \n\n You also have the right to withdraw any consent that you have given to us: \n\n i)   for the collection, use or disclosure of your personal data, and/or\nii)  for receiving marketing and promotional materials. \n\nPlease let us have any notice of withdrawal in writing, indicating your instructions clearly.\nIf you withdraw your consent for the collection, use or disclosure of your personal data, we will not however be able to provide you with the protection and services expected of us under the insurance policy that you have purchased from us.  We may then, need to cancel the policy and/or terminate your membership account with us. \nIf you withdraw your consent for receiving marketing and promotion materials, we will not be able to update you of new products and promotions.  We will put the withdrawal into effect within forty-five (45) working days of your request. \nYou may write to our Personal Data Protection Officer for the abovementioned purposes.',
  },
  {
    title: 'Feedback and Queries',
    body: 'If you have any feedback or queries in relation to the protection of your personal data, you may also write to our Personal Data Protection Officer.   We will look into your feedback or queries, and will provide you with a response within three (3) working days.  If we are unable to do so, we will inform you within three (3) working days, and shall keep you updated of our progress every seven (7) working days.',
  },
  {
    title: 'Contact Details',
    body: 'The contact details of our Personal Data Protection Officer are as follows:\n The Personal Data Protection Officer \nMSIG Insurance (Singapore) Pte. Ltd.\n4 Shenton Way\n#21-01 SGX Centre 2\nSingapore 068807\nEmail: dpo@sg.msig-asia.com\n\nIf you are still not satisfied with our response, you may write to the Personal Data Protection Commission\n(Email: info@pdpc.gov.sg or pdpc_qsm@pdpc.gov.sg). ',
  },
  {
    title: 'Changes to the Privacy Policy',
    body: 'We may amend this Privacy Policy from time to time and will place such amendments on this website. Please obtain the latest version of this Privacy Policy from our website at www.msig.com.sg.\nThis Privacy Policy is not intended to, nor does it create any contractual rights between MSIG and the policyholders.',
  },
];
