// TODO: will be remove
export const ClaimType = {
  MEDICAL: 0,
  HOSPITAL: 1,
  FLIGHT: 2,
};

export default [
  {
    type: 0,
    tripName: 'Jan Trip 1',
    status: 'Approved',
    number: '123456',
    incidentPlace: 'London, UK',
    incidentDate: '24/01/2017',
    incidentDetail: 'Fractured hand, tripped on uneven pavement',
    incidentType: 'FLIGHT DIVERSION',
    payoutAmount: '33',
    admissionDate: '24/01/2017',
    admissionTime: '10:50',
    dischargeDate: '24/01/2017',
    dischargeTime: '09:50',
    flightNumber: '50',
    inboundFlightNumber: '555',
    missFlightNumber: '555',
    reBookFlightNumber: '555',
    originalDate: '24/01/2017',
    actuallyDate: '26/01/2017',
    reasonType: 'Delay',
    currency: 'S$',
    amount: '55',
    expenseList: [{
      typeOfExpense: 'oversea medical expense',
      totalExpensesIncurred: '200',
      currency: 'S$',
      billsImage: '',
      reportImage: '',
    }, {
      typeOfExpense: 'Permanent disability (personal accident)',
      totalExpensesIncurred: '200',
      currency: 'S$',
      billsImage: '',
      reportImage: '',
    }],
    itemList: [
      {
        description: 'ABC',
        purchaseDate: '0117',
        amount: '50',
        receiptImage: '',
        damageImage: '',
        documentType: 'Passport',
        currency: 'S$',
        expenseAmount: '100',
        receiptExpenseImage: '',
        identityImage: '',
      },
      {
        description: 'ABC',
        purchaseDate: '0117',
        amount: '50',
        receiptImage: '',
        damageImage: '',
        documentType: 'Passport',
        currency: 'S$',
        expenseAmount: '100',
        receiptExpenseImage: '',
        identityImage: '',
      },
    ],
    hospitalBillsImage: '',
    hospitalDischargeImage: '',
    medicalReportImage: '',
    policeReportImage: '',
    travelImage: '',
    proofImage: '',
    airlineImage: '',
    boardingPassImage: '',
    letterImage: '',
    originalImage: '',
    disruptionImage: '',
    receiptExpenseImage: '',
    damageImage: '',
  },
  {
    type: 1,
    tripName: 'Jan Trip 1',
    status: 'Pending',
    number: '123456',
    incidentPlace: 'London, UK',
    incidentDate: '24/01/2017',
    incidentDetail: 'Fractured hand, tripped on uneven pavement',
    incidentType: 'FLIGHT DIVERSION',
    payoutAmount: '33',
    admissionDate: '24/01/2017',
    admissionTime: '10:50',
    dischargeDate: '24/01/2017',
    dischargeTime: '09:50',
    flightNumber: '50',
    inboundFlightNumber: '555',
    missFlightNumber: '555',
    reBookFlightNumber: '555',
    originalDate: '24/01/2017',
    actuallyDate: '26/01/2017',
    reasonType: 'Delay',
    currency: 'S$',
    amount: '55',
    expenseList: [{
      typeOfExpense: 'oversea medical expense',
      totalExpensesIncurred: '200',
      currency: 'S$',
      billsImage: '',
      reportImage: '',
    }, {
      typeOfExpense: 'Permanent disability (personal accident)',
      totalExpensesIncurred: '200',
      currency: 'S$',
      billsImage: '',
      reportImage: '',
    }],
    itemList: [
      {
        description: 'ABC',
        purchaseDate: '0117',
        amount: '50',
        receiptImage: '',
        damageImage: '',
        documentType: 'Passport',
        currency: 'S$',
        expenseAmount: '100',
        receiptExpenseImage: '',
        identityImage: '',
      },
      {
        description: 'ABC',
        purchaseDate: '0117',
        amount: '50',
        receiptImage: '',
        damageImage: '',
        documentType: 'Passport',
        currency: 'S$',
        expenseAmount: '100',
        receiptExpenseImage: '',
        identityImage: '',
      },
    ],
    hospitalBillsImage: '',
    hospitalDischargeImage: '',
    medicalReportImage: '',
    policeReportImage: '',
    travelImage: '',
    proofImage: '',
    airlineImage: '',
    boardingPassImage: '',
    letterImage: '',
    originalImage: '',
    disruptionImage: '',
    receiptExpenseImage: '',
    damageImage: '',
  },
  {
    type: 2,
    tripName: 'Jan Trip 1',
    status: 'Rejected',
    number: '123458',
    incidentPlace: 'London, UK',
    incidentDate: null,
    incidentDetail: 'Fractured hand, tripped on uneven pavement',
    incidentType: 'FLIGHT DIVERSION',
    payoutAmount: '33',
    admissionDate: '24/01/2017',
    admissionTime: '10:50',
    dischargeDate: '24/01/2017',
    dischargeTime: '09:50',
    flightNumber: '50',
    inboundFlightNumber: '555',
    missFlightNumber: '555',
    reBookFlightNumber: '555',
    originalDate: '24/01/2017',
    actuallyDate: '26/01/2017',
    reasonType: 'Delay',
    currency: 'S$',
    amount: '55',
    expenseList: [{
      typeOfExpense: 'oversea medical expense',
      totalExpensesIncurred: '200',
      currency: 'S$',
      billsImage: '',
      reportImage: '',
    }, {
      typeOfExpense: 'Permanent disability (personal accident)',
      totalExpensesIncurred: '200',
      currency: 'S$',
      billsImage: '',
      reportImage: '',
    }],
    itemList: [
      {
        description: 'ABC',
        purchaseDate: '0117',
        amount: '50',
        receiptImage: '',
        damageImage: '',
        documentType: 'Passport',
        currency: 'S$',
        expenseAmount: '100',
        receiptExpenseImage: '',
        identityImage: '',
      },
      {
        description: 'ABC',
        purchaseDate: '0117',
        amount: '50',
        receiptImage: '',
        damageImage: '',
        documentType: 'Passport',
        currency: 'S$',
        expenseAmount: '100',
        receiptExpenseImage: '',
        identityImage: '',
      },
    ],
    hospitalBillsImage: '',
    hospitalDischargeImage: '',
    medicalReportImage: '',
    policeReportImage: '',
    travelImage: '',
    proofImage: '',
    airlineImage: '',
    boardingPassImage: '',
    letterImage: '',
    originalImage: '',
    disruptionImage: '',
    receiptExpenseImage: '',
    damageImage: '',
  },
];
